### ISSUE TITLE
Idea: Usage tracking?!

### ISSUE THREAD

**Issue by grekko** [HTW-Webtech/ai-webtech-portal-ws-2015#3]
Do I want/need some insight what content is consumed a lot? What decisions could be derived from that information?

**Comment by maxbeier** [comment]
Steht auch schon länger auf der Liste, aber ist ein heikles Thema. Wir können ja mal™ ein Piwik aufsetzen.

**Comment by grekko** [comment]
Habe bei einigem Grübeln festgestellen, dass mir kaum sinnvolle Metriken einfallen die mir helfen könnten eine bessere Usability/Features zu iplementieren.
