### ISSUE TITLE
Idea: Add Links to edit current page on github! :)

### ISSUE THREAD

**Issue by grekko** [HTW-Webtech/ai-webtech-portal-ws-2015#4]
This way I do not fix the stuff myself but rather offer the student/consumer to fix a typo small issue him/herself!

**Comment by maxbeier** [comment]
:+1:

**Comment by grekko** [comment]
Der Edit-Link wurde mit 02ecc03 eingebaut.

@maxbeier Die ReviewEngine finde ich auch interessant. Schickst du mir den Link dann?
