### ISSUE TITLE
Idea: Inline HTML/CSS Code Editor w/ preview

### ISSUE THREAD

**Issue by grekko** [HTW-Webtech/ai-webtech-portal-ws-2015#5]
Implement an inline code-editor for the slides to show effects of css modifications in an interactive way.

**Comment by maxbeier** [comment]
Hatte sowas mal gebaut und würde es dir herauslösen, wenn du möchtest.

**Comment by grekko** [comment]
Gerne.

Ich habe jetzt angefangen http://cssdeck.com/ als Dienst zu nutzen. D.h. ich embedde die Snippets, bin damit aber aus verschiedenen Gründen noch nicht glücklich.

**Comment by maxbeier** [comment]
Ahja, hatte auch mal überlegt, alle Snippets bei JSFiddle o.ä. zu hosten und nur einzubinden. Aber rein vom Gefühl her war es dann doch besser, den Code direkt in der Präsentation und damit alles an einem Ort zu haben.

Derzeit läuft es so: Das [Jekyll-Tag](https://github.com/HTW-Webtech/Kursseite/blob/master/_plugins/liquid-editor.rb) nimmt Code-Comments entgegen und wrappt entsprechend HTML drum herum. (Die Backslashes im Beispiel sind nur, weil ich nicht weiß, wie man in Markdown escaped 😬)

```
{% editor auto hide-html %}
\```html
<div class="custom-box">A A A A A A</div>
<div class="custom-box">B B B B B B B B B</div>
<div class="custom-box">C C C C C C C C C C C C</div>
<div class="custom-box">D D D D D D D D D D D D D D D D D D</div>
\```
\```css
.custom-box {
   float: left;
   width: 50px;
   height: 50px;
   margin: 10px;
   padding: 20px;
   border: 10px solid hotpink;
   background-color: skyblue;
   /* box-sizing: border-box; */
}
\```
{% endeditor %}
```

Auto gibt hierbei an, wie der Raum verteilt werden soll. `hide-*` sorgt dafür, dass einzelne Sprachen in die Vorschau mit einfließen, aber kein eigener Editor angezeigt wird.

Dann gibt es noch ein kleines [Skriptchen](https://github.com/HTW-Webtech/Kursseite/blob/master/assets/scripts/editor.js) und die [Styles](https://github.com/HTW-Webtech/Kursseite/blob/master/_sass/_editor.scss).

Hoffe das hilft.

**Comment by grekko** [comment]
Vor kurzem habe ich mein Seite dank LetsEncrypt auf HTTPs/SSL umgestellt und mein externer Code-Editor unterstützt derzeit nur HTTP. Entsprechend funktioniert der externe Editor nicht mehr. Wenn das Problem bis Mitte Januar nicht gelöst ist, wird ein eigener interner Editor wieder interessanter.
